name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o YMDS-Windows.exe YMDS.go

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o YMDS-Linux YMDS.go

      - name: Build MacOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -o YMDS-MacOS-Intel YMDS.go

      - name: Build MacOS (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -o YMDS-MacOS-AppleSilicon YMDS.go

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            YMDS-Windows.exe
            YMDS-Linux
            YMDS-MacOS-Intel
            YMDS-MacOS-AppleSilicon
            YMDS-Userscript.js
